CREATE TABLE [elections].[StateElectoralUnitOverview]
(
	[Id] INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	[AbsenceAndMobileTeamVotes] INT NOT NULL,
	[ElectionYear] INT NOT NULL,
	[ConfirmedVotes] INT NOT NULL,
	[DataFrom] DATETIME2 NOT NULL,
	[ElectoralUnit] INT NOT NULL,
	[NumberOfVoters] INT NOT NULL,
	[PartyNumber] INT NOT NULL,
	[RegularVotes] INT NOT NULL,
	[TotalMandates] INT NOT NULL,
	[TotalVotes] INT NOT NULL,
	[TotalNoVotes] INT NOT NULL,
	[ValidVotes] INT NOT NULL,
	[TotalInvalidVotes] INT NOT NULL,
	[InvalidBlankBallots] INT NOT NULL,
	[InvalidOthersBallots] INT NOT NULL,
	[PercentageProcessedPollingStations] DECIMAL(18, 2) NOT NULL,
	[PercentageTotalVotes] DECIMAL(18, 2) NOT NULL,
	[PercentageTotalNoVotes] DECIMAL(18, 2) NOT NULL,
	[ProcessedInvalidBlankBallots] DECIMAL(18, 2) NOT NULL,
	[ProcessedInvalidOthersBallots] DECIMAL(18, 2) NOT NULL,
	[ProcessedConfirmedVotes] DECIMAL(18, 2) NOT NULL,
	[PostOfficeVotes] DECIMAL(18, 2) NOT NULL,
	[ProcessedAbsenceAndMobileTeamVotes] DECIMAL(18, 2) NOT NULL,
	[ProcessedPostOfficeVotes] DECIMAL(18, 2) NOT NULL,
	[ProcessedRegularVotes] DECIMAL(18, 2) NOT NULL,
	[ProcessedValidVotes] DECIMAL(18, 2) NOT NULL,
	[TotalPollingStations] INT NOT NULL,
	[ProcessedPollingStations] INT NOT NULL,
	[CandidatesNumber] INT NOT NULL
)
