IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Users' AND COLUMN_NAME = 'PasswordResetToken')
    ALTER TABLE dbo.Users ADD PasswordResetToken NVARCHAR(16) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Users' AND COLUMN_NAME = 'PasswordResetTokenExpiry')
    ALTER TABLE dbo.Users ADD PasswordResetTokenExpiry DATETIME2 NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Users' AND COLUMN_NAME = 'MustChangePassword')
    ALTER TABLE dbo.Users ADD MustChangePassword BIT NOT NULL DEFAULT 0;
