IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Users' AND COLUMN_NAME = 'MustChangePassword')
    ALTER TABLE dbo.Users DROP COLUMN MustChangePassword;
