CREATE TABLE [elections].[EntityPresidentOverview]
(
	[Id] INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [ElectionYear] INT NOT NULL,
    [Entity] INT NOT NULL,
    [AbsenceAndMobileTeamVotes] INT NOT NULL,
    [BasicInfoId] INT NOT NULL,
    [ConfirmedVotes] INT NOT NULL,
    [DataFrom] DATETIME2 NOT NULL,
    [InvalidBlankBallots] INT NOT NULL,
    [InvalidOthersBallots] INT NOT NULL,
    [NumberOfCandidates] INT NOT NULL,
    [NumberOFMunicipalities] INT NOT NULL,
    [NumberOfVoters] INT NOT NULL,
    [PercentageProcessedPollingStations] DECIMAL NOT NULL,
    [PercentageTotalNoVotes] DECIMAL NOT NULL,
    [PercentageTotalVotes] DECIMAL NOT NULL,
    [PostOfficeVotes] DECIMAL NOT NULL,
    [ProcessedAbsenceAndMobileTeamVotes] DECIMAL NOT NULL,
    [ProcessedConfirmedVotes] DECIMAL NOT NULL,
    [ProcessedInvalidBlankBallots] DECIMAL NOT NULL,
    [ProcessedInvalidOthersBallots] DECIMAL NOT NULL,
    [ProcessedPollingStations] INT NOT NULL,
    [ProcessedPostOfficeVotes] DECIMAL NOT NULL,
    [ProcessedRegularVotes] DECIMAL NOT NULL,
    [ProcessedTotalInvalidVotes] DECIMAL NOT NULL,
    [ProcessedValidVotes] DECIMAL NOT NULL,
    [RegularVotes] INT NOT NULL,
    [TotalInvalidVotes] INT NOT NULL,
    [TotalNoVotes] INT NOT NULL,
    [TotalPollingStations] INT NOT NULL,
    [TotalVotes] INT NOT NULL,
    [ValidVotes] INT NOT NULL
)
