<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>8dd5476e-c8cb-48b5-93c9-20f1bfc62775</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<LangVersion>latest</LangVersion>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="App.config" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\.editorconfig" Link=".editorconfig" />
		<None Include="App.config" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.14.2" />
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
		<PackageReference Include="QuestPDF" Version="2024.3.4" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.4.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Boundary\Boundary.csproj" />
		<ProjectReference Include="..\DAL\DAL.csproj" />
	</ItemGroup>

</Project>
